books:
  max-book-page-size: 2560
  max-book-total-size-multiplier: 0.98
limits:
  ## There is no perfect value for this.
  ## On 1.8, you should be able to get away with 200-300.
  ## On 1.18.2, you may need to increase this from 700.
  ## In order to prevent people getting kicked for lag, the max PPS is higher than shown below.
  ## Every server is different, you'll have to find a good value yourself.
  max-packets-per-second: 700
